[env:esp32dev]
platform = espressif32
board    = esp32dev
framework = arduino

; Build flags – enable BT Classic (disables BLE to save RAM/power)
build_flags =
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_CLASSIC_BT_ENABLED=1
    -DCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=1
    -DCONFIG_BT_BLE_ENABLED=0

monitor_speed = 115200
